### ISSUE TITLE
Error loading the library

### ISSUE THREAD

**Issue by hopewise** [waneck/systools#14]
I've installed systools, but I get this error when trying to run Windows target:

Could not load module systools@systools_init_0

Any idea?

**Comment by IBwWG** [comment]
Hi,

I had this same error crop up for someone testing my game on Windows.  On my Windows box it worked fine, but not theirs.  I managed to fix it for them, so now my openfl/haxeflixel project.xml has:

``` xml
    <!-- systools needs both these lines to distribute properly -->
    <haxelib name="systools"/>
    <ndll name="systools" haxelib="systools" />
```

However, I am again having this on Linux, despite that line.  On my Linux Mint 17.3 (32-bit) box it works fine, but on another person's Ubuntu 15.10 install, it crashes on startup with:

```
Called from systools.Loader::load systools/Loader.hx line 20
Called from cpp.Lib::load /usr/lib/haxe/std/cpp/Lib.hx line 34
Error : Could not load module systools@systools_init__0
```

Do you have any other hints for forcing the ndll to be copied correctly on build?  (I'm assuming it's more or less the same cause this time around, a missing library file.)

Thanks very much for any help.

**Comment by 01010111** [comment]
Had the same issue on OSX (Sierra), added 
```<ndll name="systools" haxelib="systools" />```
and it resolved it
