### ISSUE TITLE
Open File Dialogue bug [Fixed]

### ISSUE THREAD

**Issue by BluFedora** [waneck/systools#21]
How would I test to see if the dialogue was canceled ?
if the dialogue is canceled then it will crash  

var result = Dialogs.openFile
(
    "Select a Map File",
    "Test Message",
    filter
);

// I Tried This 
if (result.length > 0)
{
     trace(result[0]);
}

// I've also tried this
if (result != null || result != "")
{
     trace(result[0]);
}

This just crashes the program.
Is there a way to see/handle a canceled open dialogue ? thanks if someone can help
-Blufedora

**Comment by Tiago-Ling** [comment]
I'm using the `openFile` command without any problem in Windows.

Try this:

```haxe
var result = Dialogs.openFile(...);
if (result != null) {
    trace(result);    //Will return an Array<String> of file paths
    //Do anything with the filepaths returned
}
```

In your last try there is an error in assuming that `result` is a String.
