### ISSUE TITLE
Neko - Failed to load library

### ISSUE THREAD

**Issue by Tiago-Ling** [waneck/systools#23]
Trying to use the library in Windows with **Haxe 3.1.3**, **Neko 2.0.0** and **OpenFL 2.2.4** i get the following error when targetting neko:

```
Called from systools/Dialogs.hx line 36
Called from systools/Loader.hx line 18
Called from systools/Loader.hx line 30
Called from C:\HaxeToolkit\haxe\std/neko/Lib.hx line 30
Uncaught exception - load.c(237) : Failed to load library : systools.ndll
```
I'm using **systools 1.1.0** from haxelib. The library loads and works fine with windows platform, this problem only happens with Neko.

I figure i might be doing something wrong or the dialogs might work in cpp target only, but seeing the samples that not seems to be the case. Any advice?

Thanks!

**Comment by waneck** [comment]
That's strange. The ndlls should work on neko too.
Can you try recompiling the ndll? Just run `haxelib run hxcpp Build.xml` at the `project` directory

**Comment by waneck** [comment]
Can you try the samples and see if they work for you?

**Comment by Tiago-Ling** [comment]
Hi Cauê,

Recompiling the ndll does not solve the problem - here is the output: [systools.ndll output](http://hastebin.com/eyuqucuxut.tex)

I tested the samples `3`, `5` and `6` - all of them are working fine (tested compiling and running them directly through the command prompt). The problem does not happen with pure Haxe it seems.

The error appears to be related to Lime / OpenFL - trying to build and run from both FlashDevelop and command prompt returns the same error.

**Comment by waneck** [comment]
I'm not sure I can help then, as it seems the issue is with OpenFL. IIRC, OpenFL used to do some tinkering with the special load function on neko. Maybe it's not looking for haxelib directories?
Try to compile your app with -D neko_source, and look for anything that sets the `$loader.path` type. In a healthy version, it should be something like:
```
    $loader.path = $array("/path/to/systools/ndll/" + @s,$loader.path);
```

**Comment by Tiago-Ling** [comment]
Yes, OpenFL ignores the ndlls completely by default. Here is the `$loader.path` values:
```neko
$loader.path = $array(haxe.io.Path.directory(Sys.executablePath()),$loader.path);
$loader.path = $array(String.new("./"),$loader.path);
$loader.path = $array(String.new("@executable_path/"),$loader.path);
```

However, i just found out you can manually include the native library in your OpenFL app by using the following command in `project.xml` (just after the `<haxelib name="systools" />` tag):
```xml
<ndll name="systools" haxelib="systools" />
```
I suppose this is a requirement to use libraries with `ndll`s in OpenFL for the Neko platform. I'm closing the issue since the problem has been solved. 

Also, this information could be in the `readme.md` file to prevent other users from recreating this issue. I'm gonna make a pull request with these instructions, but if you prefer to write it yourself fell free to ignore / close it. 

Thanks for the help!
