### ISSUE TITLE
"Could not find primitive dialogs_save_file__4." on Linux

### ISSUE THREAD

**Issue by Jacic** [waneck/systools#9]
Just as the title says. The message is output at runtime (project compiles fine) whether or not I try to use the save file dialog, but if I try to use it, I see that there is a problem related to line 49 of Dialogs.hx:
"Null Function Pointer
<snip most of callback>
Called from systools.Dialogs.saveFile (systools/Dialogs.hx line 49)"

Unfortunately, I was planning on using the save file dialog for my current project. I'll happily provide further information, if needed.

**Comment by waneck** [comment]
This was fixed at 0616703f2c2cbbbf41c94465f206b80a5c4533fc
